languaje: node_js
node_js:
  - "12.8.0"

services:
  - docker

notifications:
  slack: intersysconsulting:nmWMXBTwVudJi3WB4C1xWwxm

branches:
  only:
    - development

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - docker build . -t ingangsters/flask-ecommerce -f Dockerfile

script:
  - docker run -e CI=true -e AWS_BUCKET_NAME=$AWS_BUCKET_NAME -e AWS_SECRET_KEY=$AWS_SECRET_KEY -e AWS_BUCKET_NAME=$AWS_BUCKET_NAME -e MONGO_URI=$MONGO_URI -e JWT_SECRET_KEY=$JWT_SECRET_KEY -p 5000:8080 -d ingangsters/flask-ecommerce
  - node_modules/.bin/newman run positive_tests.postman_collection.json

deploy:
  provider: elasticbeanstalk
  on:
    all_branches: true
  access_key_id:
    secure: "$EB_AWS_KEY_ID"
  secret_access_key:
    secure: "$EB_AWS_SECRET_KEY"
  region: "us-east-2"
  app: "ecommerce"
  env: "ecommerce-test"
  bucket_name: "elasticbeanstalk-us-east-2-255496091602"
